<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>dalaran-parent</artifactId>
        <groupId>io.terminus</groupId>
        <version>2.4.8-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>dalaran-component</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>dalaran-http</module>
        <module>dalaran-common</module>
        <module>dalaran-function</module>
        <module>dalaran-mapper</module>
        <module>dalaran-rocketmq</module>
        <module>dalaran-dubbo</module>
        <module>dalaran-kafka</module>
        <module>dalaran-soap</module>
        <module>dalaran-mail</module>
        <module>dalaran-ftp</module>
        <module>dalaran-route</module>
        <module>dalaran-loopwhile</module>
        <module>dalaran-foreach</module>
        <module>dalaran-sql</module>
        <module>dalaran-service</module>
        <module>dalaran-errorcatch</module>
        <module>dalaran-script</module>
        <module>dalaran-as2</module>
        <module>dalaran-retry</module>
        <module>dalaran-subflow</module>
        <module>dalaran-multicast</module>
        <module>dalaran-end</module>
        <module>dalaran-elasticjob</module>
        <module>dalaran-csb</module>
    </modules>

</project>