spring:
  application:
    name: dalaran-runtime
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:11.107.21.224}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:dalaran}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${MYSQL_USERNAME:mysql}
    password: ${MYSQL_PASSWORD:fc9ef64565d7420aaa1d7955ea09fb02}
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect