<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>dalaran-parent</artifactId>
        <groupId>io.terminus</groupId>
        <version>2.4.8.4-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>dalaran-as2-server</artifactId>

    <dependencies>
<!--        <dependency>-->
<!--            <groupId>io.terminus</groupId>-->
<!--            <artifactId>dalaran-components</artifactId>-->
<!--            <version>${project.version}</version>-->
<!--        </dependency>-->

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-resource-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-http</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-function</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-mapper</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-rocketmq</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-dubbo</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-kafka</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-soap</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-mail</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-ftp</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-route</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-loopwhile</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-foreach</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-sql</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-service</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-errorcatch</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-scheduler</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-script</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-as2</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-retry</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-subflow</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-multicast</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-end</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.terminus</groupId>
            <artifactId>dalaran-elasticjob</artifactId>
            <version>${project.version}</version>
        </dependency>


        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.199</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src/main/java</sourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>