spring:
  application:
    name: default-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:dalaran}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:anywhere}
  jpa.hibernate.ddl-auto: update
  jpa.database-platform: org.hibernate.dialect.MySQLDialect