server:
  port: 8088
  session:
    timeout: 10400
spring:
  application:
    name: dalaran-console
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:dalaran}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:secret}
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
  security:
    user:
      name: ${SECURITY_USERNAME:terminus}
      password: ${SECURITY_PASSWORD:anywhere}
      role: ${SECURITY_ROLE:USER}
    ant-matchers: ${ANT_MATCHERS:/api/platform/login/auth}